[package]
name = "phi-save-data"
version = "0.1.5"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.3"
csv = "1.1"
xlsxwriter = "0.6.1"
rayon = "1.6"
serde_json = "1.0"

[dev-dependencies]
# Add any test-specific dependencies here