name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Rust 工具链
        uses: actions/setup-rust@v1
        with:
          profile: minimal
          toolchain: stable

      - name: 构建项目
        run: cargo build --release

      - name: 创建发布版本
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: 上传构建产物
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            target/release/$(if [ $RUNNER_OS == 'Windows' ]; then echo 'PhiSaveSong.exe'; else echo 'PhiSaveSong'; fi)
          asset_name: $(if [ $RUNNER_OS == 'Windows' ]; then echo 'PhiSaveSong.exe'; else echo 'PhiSaveSong'; fi)
          asset_content_type: application/octet-stream
